name: ttclust
channels:
- defaults
- conda-forge
dependencies:
- argcomplete
- cython
- progressbar2
- matplotlib
- numpy
- pandas
- scipy >= 0.18
- mdtraj
- scikit-learn
- prettytable
- numba
- hashlib
